spring.application.name=calorie_tracker

# DataSource
spring.datasource.url=jdbc:postgresql://ep-morning-band-aku6kycv-pooler.c-3.us-west-2.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_SG5g1KfuJroV
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true